import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Roboto } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import { muiTheme } from "@/theme";
import { Container, Stack } from "@mui/material";
import { AppDrawer } from "@/components/AppDrawer";
import { Body } from "@/components/Body";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Chat GPT Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <Body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={muiTheme}>
            <Stack direction="row">
              <AppDrawer isDesktop menuItems={[]} />
              <Container>{children}</Container>
            </Stack>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </Body>
    </html>
  );
}
